### ISSUE TITLE
Doesn't seem to work on PyCharm nor PhpStorm

### ISSUE THREAD

**Issue by aramhovsepyan** [semgrep/semgrep-intellij#24]
Hi,

I haven't had any luck with this plugin. I have installed semgrep on the command line and it works perfectly fine. The semgrep plugin is installed on the IntelliJ IDE and I can click on the semgrep button in the IDE. However nothing happens when I click on any of the actions (e.g., Scan Workspace with Semgrep, Sign In, Sign out with semgrep).

The unofficial semgrep plugin does work (but has limitations).

Anything I'm doing wrong?
Thanks for the help.

**Comment by ajbt200128** [comment]
closing as this seems solved in #31
